Repository data-integrations/google-cloud, pull requests merged in 2020-12, with the labels that each got.

#448 [PLUGIN-204] fix gcs sink error message
  src/main/java/io/cdap/plugin/gcp/gcs/sink/GCSBatchSink.java
Labels: 6.3

#450 [PLUGIN-204] fix gcs sink error message
  src/main/java/io/cdap/plugin/gcp/gcs/sink/GCSBatchSink.java
Labels: 6.3

#453 [CDAP-17473] Fix gcs source auto schema detection
  src/main/java/io/cdap/plugin/gcp/gcs/source/GCSSource.java
Labels: 6.3

#458 Fix schema auto detection
  src/main/java/io/cdap/plugin/gcp/gcs/source/GCSSource.java
Labels: 6.3

#455 [CDAP-17473] Fix gcs source auto schema detection
  src/main/java/io/cdap/plugin/gcp/gcs/source/GCSSource.java
Labels: 6.1

#454 [CDAP-17473] Fix gcs source auto schema detection
  src/main/java/io/cdap/plugin/gcp/gcs/source/GCSSource.java
Labels: 6.2

#452 [CDAP-17473] Fix gcs source auto schema detection
  src/main/java/io/cdap/plugin/gcp/gcs/source/GCSSource.java
Labels: 6.4

#468 [PLUGIN-518] Datastore namespace doc fix
  docs/Datastore-batchsink.md
  docs/Datastore-batchsource.md
  src/main/java/io/cdap/plugin/gcp/datastore/sink/DatastoreSinkConfig.java
  src/main/java/io/cdap/plugin/gcp/datastore/source/DatastoreSource.java
  src/main/java/io/cdap/plugin/gcp/datastore/source/DatastoreSourceConfig.java
  src/main/java/io/cdap/plugin/gcp/datastore/util/DatastorePropertyUtil.java
Labels: 6.4

#474 Fixed the issue with error logs in PLUGIN-234
  src/main/java/io/cdap/plugin/gcp/spanner/source/SpannerRecordReader.java
Labels: 6.1
