Repository data-integrations/google-cloud, pull requests merged in 2020-08, with the labels that each got.

#284 Enable GCS Batch Sink to take file system properties
  docs/GCS-batchsink.md
  src/main/java/io/cdap/plugin/gcp/gcs/sink/GCSBatchSink.java
  src/test/java/io/cdap/plugin/gcp/gcs/sink/GCSBatchSinkTest.java
  widgets/GCS-batchsink.json
Labels: 6.1, cherry-pick

#283 Enable GCS Batch Sink to take file system properties
  docs/GCS-batchsink.md
  src/main/java/io/cdap/plugin/gcp/gcs/sink/GCSBatchSink.java
  src/test/java/io/cdap/plugin/gcp/gcs/sink/GCSBatchSinkTest.java
  widgets/GCS-batchsink.json
Labels: 6.2, cherry-pick

#288 [CDAP-16999] GCSSource Revert 0.15
  src/main/java/io/cdap/plugin/gcp/gcs/source/GCSSource.java
Labels: 6.2, bug, cherry-pick

#289 [CDAP-16999] GCSSource Revert 0.14
  src/main/java/io/cdap/plugin/gcp/gcs/source/GCSSource.java
Labels: 6.1, bug, cherry-pick
