Repository data-integrations/google-cloud, pull requests merged in 2021-08, with the labels that each got.

#744 [CDAP-18294] Update Pushdown ui strings
  src/main/java/io/cdap/plugin/gcp/bigquery/sqlengine/BigQuerySQLEngineConfig.java
  widgets/BigQueryPushdownEngine-sqlengine.json
Labels: cherry-pick

#741 Fixed Pub/Sub subscriber for Spark3 compatibility
  src/main/java/io/cdap/plugin/gcp/publisher/source/PubSubSubscriberUtil.java
Labels: build

#738 [PLUGIN-731] Added support for BIGNUMERIC for BigQuery Source and Sink (Type is ch…
  src/main/java/io/cdap/plugin/gcp/bigquery/sink/BigQuerySinkUtils.java
  src/main/java/io/cdap/plugin/gcp/bigquery/util/BigQueryDataParser.java
  src/main/java/io/cdap/plugin/gcp/bigquery/util/BigQueryTypeSize.java
  src/main/java/io/cdap/plugin/gcp/bigquery/util/BigQueryUtil.java
  src/test/java/io/cdap/plugin/gcp/bigquery/util/BigQueryUtilTest.java
Labels: build

#736 [CDAP-17928] We use hierarchical naming as the record name to ensure each record will ha…
  src/main/java/io/cdap/plugin/gcp/bigquery/util/BigQueryUtil.java
  src/test/java/io/cdap/plugin/gcp/bigquery/util/BigQueryUtilTest.java
Labels: build

#739 [Plugin-704] Fixes UPSERT with no Table not following partition options
  src/main/java/io/cdap/plugin/gcp/bigquery/sink/BigQueryOutputFormat.java
Labels: build

#749 Fixed issue with BQ Pushdown temporary buckets not getting deleted after pipeline execution
  src/main/java/io/cdap/plugin/gcp/bigquery/sink/AbstractBigQuerySink.java
  src/main/java/io/cdap/plugin/gcp/bigquery/sink/BigQuerySinkUtils.java
  src/main/java/io/cdap/plugin/gcp/bigquery/sqlengine/BigQueryPushDataset.java
  src/main/java/io/cdap/plugin/gcp/bigquery/sqlengine/BigQuerySQLEngine.java
Labels: build

#750 Fixed issue with BQ Pushdown temporary buckets not getting deleted after pipeline execution
  src/main/java/io/cdap/plugin/gcp/bigquery/sink/AbstractBigQuerySink.java
  src/main/java/io/cdap/plugin/gcp/bigquery/sink/BigQuerySinkUtils.java
  src/main/java/io/cdap/plugin/gcp/bigquery/sqlengine/BigQueryPushDataset.java
  src/main/java/io/cdap/plugin/gcp/bigquery/sqlengine/BigQuerySQLEngine.java
Labels: build

#755 Fix bug in setting temporary bucket name in BQ multisink
  src/main/java/io/cdap/plugin/gcp/bigquery/sink/BigQueryMultiSink.java
Labels: build

#752 Fix BQ plugin documentation
  docs/BigQueryMultiTable-batchsink.md
  docs/BigQueryTable-batchsink.md
  docs/BigQueryTable-batchsource.md
  src/main/java/io/cdap/plugin/gcp/bigquery/common/BigQueryBaseConfig.java
  src/main/java/io/cdap/plugin/gcp/bigquery/source/BigQuerySourceConfig.java
Labels: build

#763 Fixed issue with GCS Source temp buckets not getting deleted after pipeline execution
  src/main/java/io/cdap/plugin/gcp/bigquery/source/BigQuerySourceUtils.java
Labels: build

#764 [Cherry-Pick][0.18] Fixed issue with GCS Source temp buckets not getting deleted after pipeline execution
  src/main/java/io/cdap/plugin/gcp/bigquery/source/BigQuerySourceUtils.java
Labels: build

#766 [RELEASE-6.5.0] Bump to SNAPSHOT
  pom.xml
Labels: automated-release
