Repository data-integrations/google-cloud, pull requests merged in 2021-01, with the labels that each got.

#456 Fixed: PLUGIN-499
  src/main/java/io/cdap/plugin/gcp/bigquery/source/BigQuerySource.java
  src/main/java/io/cdap/plugin/gcp/bigquery/source/PartitionedBigQueryInputFormat.java
  src/main/java/io/cdap/plugin/gcp/bigquery/util/BigQueryConstants.java
Labels: 6.4

#482 [PLUGIN-522] Fix macro for bigtable sink
  src/main/java/io/cdap/plugin/gcp/bigtable/sink/BigtableSink.java
Labels: 6.4

#485 [PLUGIN-522] Fix macro for bigtable sink
  src/main/java/io/cdap/plugin/gcp/bigtable/sink/BigtableSink.java
Labels: 6.1

#483 [PLUGIN-522] Fix macro for bigtable sink
  src/main/java/io/cdap/plugin/gcp/bigtable/sink/BigtableSink.java
Labels: 6.3

#478 [PLUGIN-518] Datastore namespace doc fix
  docs/Datastore-batchsink.md
  docs/Datastore-batchsource.md
  src/main/java/io/cdap/plugin/gcp/datastore/sink/DatastoreSinkConfig.java
  src/main/java/io/cdap/plugin/gcp/datastore/source/DatastoreSource.java
  src/main/java/io/cdap/plugin/gcp/datastore/source/DatastoreSourceConfig.java
  src/main/java/io/cdap/plugin/gcp/datastore/util/DatastorePropertyUtil.java
Labels: 6.1

#476 [PLUGIN-518] Datastore namespace doc fix
  docs/Datastore-batchsink.md
  docs/Datastore-batchsource.md
  src/main/java/io/cdap/plugin/gcp/datastore/sink/DatastoreSinkConfig.java
  src/main/java/io/cdap/plugin/gcp/datastore/source/DatastoreSource.java
  src/main/java/io/cdap/plugin/gcp/datastore/source/DatastoreSourceConfig.java
  src/main/java/io/cdap/plugin/gcp/datastore/util/DatastorePropertyUtil.java
Labels: 6.3

#477 [PLUGIN-518] Datastore namespace doc fix
  docs/Datastore-batchsink.md
  docs/Datastore-batchsource.md
  src/main/java/io/cdap/plugin/gcp/datastore/sink/DatastoreSinkConfig.java
  src/main/java/io/cdap/plugin/gcp/datastore/source/DatastoreSource.java
  src/main/java/io/cdap/plugin/gcp/datastore/source/DatastoreSourceConfig.java
  src/main/java/io/cdap/plugin/gcp/datastore/util/DatastorePropertyUtil.java
Labels: 6.2

#479 [PLUGIN-513] Dont allow captial letters in GCS bucket
  src/main/java/io/cdap/plugin/gcp/gcs/GCSPath.java
Labels: 6.3

#480 [PLUGIN-513] Dont allow captial letters in GCS bucket
  src/main/java/io/cdap/plugin/gcp/gcs/GCSPath.java
Labels: 6.2

#481 [PLUGIN-513] Dont allow captial letters in GCS bucket
  src/main/java/io/cdap/plugin/gcp/gcs/GCSPath.java
Labels: 6.1

#491 CherryPick for release 0.14
  src/main/java/io/cdap/plugin/gcp/bigquery/sink/AbstractBigQuerySink.java
  src/test/java/io/cdap/plugin/gcp/bigquery/sink/BigQuerySinkTest.java
Labels: 6.1

#492 CherryPick for release/0.15
  src/main/java/io/cdap/plugin/gcp/bigquery/sink/AbstractBigQuerySink.java
  src/test/java/io/cdap/plugin/gcp/bigquery/sink/BigQuerySinkTest.java
Labels: 6.2

#503 Revert "[CDAP-17473] Fix gcs source auto schema detection"
  src/main/java/io/cdap/plugin/gcp/gcs/source/GCSSource.java
Labels: 6.2

#504 Revert "[CDAP-17473] Fix gcs source auto schema detection"
  src/main/java/io/cdap/plugin/gcp/gcs/source/GCSSource.java
Labels: 6.1

#508 Revert "Revert "[CDAP-17473] Fix gcs source auto schema detection""
  src/main/java/io/cdap/plugin/gcp/gcs/source/GCSSource.java
Labels: 6.1

#511 "Revert "[CDAP-17473] Fix gcs source auto schema detection"
  src/main/java/io/cdap/plugin/gcp/gcs/source/GCSSource.java
Labels: 6.1

#513 Version bump
  pom.xml
Labels: 6.1

#514 version bump to snapshot
  pom.xml
Labels: 6.1

#462 Plugin-498: Added content-type to GCS sink
  docs/GCS-batchsink.md
  src/main/java/io/cdap/plugin/gcp/gcs/sink/GCSBatchSink.java
  src/main/java/io/cdap/plugin/gcp/gcs/sink/GCSMultiBatchSink.java
  src/main/java/io/cdap/plugin/gcp/gcs/sink/GCSOutputCommitter.java
  src/main/java/io/cdap/plugin/gcp/gcs/sink/GCSOutputFormatProvider.java
  src/main/java/io/cdap/plugin/gcp/gcs/sink/RecordFilterOutputFormat.java
  src/test/java/io/cdap/plugin/gcp/gcs/sink/GCSBatchSinkTest.java
  src/test/java/io/cdap/plugin/gcp/gcs/sink/GCSOutputformatProviderTest.java
  widgets/GCS-batchsink.json
  widgets/GCSMultiFiles-batchsink.json
Labels: 6.4

#518 CherryPick for release/0.16 - PLUGIN-498
  docs/GCS-batchsink.md
  src/main/java/io/cdap/plugin/gcp/gcs/sink/GCSBatchSink.java
  src/main/java/io/cdap/plugin/gcp/gcs/sink/GCSMultiBatchSink.java
  src/main/java/io/cdap/plugin/gcp/gcs/sink/GCSOutputCommitter.java
  src/main/java/io/cdap/plugin/gcp/gcs/sink/GCSOutputFormatProvider.java
  src/main/java/io/cdap/plugin/gcp/gcs/sink/RecordFilterOutputFormat.java
  src/test/java/io/cdap/plugin/gcp/gcs/sink/GCSBatchSinkTest.java
  src/test/java/io/cdap/plugin/gcp/gcs/sink/GCSOutputformatProviderTest.java
  widgets/GCS-batchsink.json
  widgets/GCSMultiFiles-batchsink.json
Labels: on-hold-63

#494 CherryPick for release/0.16
  src/main/java/io/cdap/plugin/gcp/bigquery/source/BigQuerySource.java
  src/main/java/io/cdap/plugin/gcp/bigquery/source/PartitionedBigQueryInputFormat.java
  src/main/java/io/cdap/plugin/gcp/bigquery/util/BigQueryConstants.java
Labels: on-hold-63

#493 CherryPick for release/0.16
  src/main/java/io/cdap/plugin/gcp/bigquery/sink/AbstractBigQuerySink.java
  src/test/java/io/cdap/plugin/gcp/bigquery/sink/BigQuerySinkTest.java
Labels: 6.3, on-hold-63

#470 Cherry Pick for PLUGIN-234 in release 0.16
  src/main/java/io/cdap/plugin/gcp/spanner/source/SpannerRecordReader.java
Labels: 6.3, on-hold-63

#457 updated/PLUGIN-296
  docs/Spanner-batchsource.md
  src/main/java/io/cdap/plugin/gcp/spanner/source/SpannerSource.java
Labels: 6.4
